### ISSUE TITLE
jdbc_fetch_size no effect?

### ISSUE THREAD

**Issue by LxiaoGirl** [logstash-plugins/logstash-input-jdbc#103]
logstash 1.5.5
jdbc 1.0.0

error log:
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid24312.hprof ...
Heap dump file created [1159466364 bytes in 21.477 secs]

i read 
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html#plugins-inputs-jdbc-jdbc_page_size
add parameter jdbc_fetch_size.
but,no effect.
I want to increase memory?

**Comment by jaykay153** [comment]
This isn't working for me either using postgresql. Looking at the postgres documentation, the code needs to explicitly set the connection autocommit mode to false e.g. conn.setAutoCommit(false);
https://jdbc.postgresql.org/documentation/91/query.html#fetchsize-example

For data size of 10 million plus, this is a must (jdbc_paging_enabled is too slow).

**Comment by jaykay153** [comment]
Can this be prioritized please?

**Comment by suyograo** [comment]
thanks for the issue, we'll get this soon.

**Comment by LxiaoGirl** [comment]
fixed?

**Comment by edeak** [comment]
I guess pagination could be made faster if the following statement is executed:
select t.* from (select id from t where id > :LAST_ID limit :LIMIT) q join t on q.id = t.id

I use this trick to iterate through millions of records and its quite fast, the only thing to be solved is getting the last id and use it as a variable inside the plugin.

**Comment by untergeek** [comment]
> the only thing to be solved is getting the last id and use it as a variable inside the plugin.

This was committed in #108 and can be gained by updating to version 3.0.0 of the plugin.

Some interim documentation: https://github.com/logstash-plugins/logstash-input-jdbc/issues/57#issuecomment-169436652

**Comment by jaykay153** [comment]
Many tables don't have the last ID column. What about the jdbc_fetch_size fix please?

**Comment by jjunqueira** [comment]
+1, please fix! 

The paging is slower and because of the way that the count query is implemented for paging(just by wrapping the defined statement) I am seeing Incorrect Key File errors in MySQL.

An alternative might also be allowing a way to define the count query statement?

Let me know if I can do anything to help. Thank you for your hard work on this project!

**Comment by rspuler** [comment]
Serious problem for me too. This plugin does not work with postgresql driver and full import of big tables. Allways results in an OutOfMemoryError due to the reason that  jaykay153 has given.

**Comment by rspuler** [comment]
Workaround is not to use the official postgresql drivers but this one here:
https://github.com/impossibl/pgjdbc-ng which seams to work (probably be setting autocommit to false, when fetchSize is set)

**Comment by axhiao** [comment]
Does this parameter work under MySQL-JDBC?

**Comment by axhiao** [comment]
It seems that an additional parameter `?useCursorFetch=true` needs to be added to the connection string of mysql 5.x.

**Comment by njvack** [comment]
It sounds as though the logstash jdbc plugin itself can't force the connection to use a cursor for fetching rows; you need to tell the JDBC driver to do it. That's okay. However! It would be very very helpful if the plugin raised a big warning if you try to set jdbc_fetch_size and your connection doesn't support it. Or at least mention this in the documentation.

For MySQL users, @axhiao is right; using useCursorFetch=true in your connect string lets you import all the rows without problem.

**Comment by ryanrozich** [comment]
Trying to do a big load from redshift (10's of millions of rows) into elasticsearch. Gave logstash 12G of heap and it still ran out of memory. jdbc_fetch_size was set to 10000 - it looks like this is my problem.

Also looks like for redshfit, there are no driver configuration options that let you set autocommit to off. 

http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-options.html

You get an error from your SQL if you try to using `set autocommit=off;`  the error says 

```ERROR:  SET AUTOCOMMIT TO OFF is no longer supported```

Agree that if fetch size will not work there should at least be a big error printed to avoid needing to find this page to explain whats happening. 

Wouldn't it be better to have the JDBC input set AutoCommit(false) whenever `jdbc_fetch_size` param is set? 

Any other ideas for how to get large amounts of data out of Redshift and into ES using logstash without running out of memory?

**Comment by tsingyi** [comment]
@rspuler is pgjdbc-ng still working? I got error message like:

```
No serializer found for class com.impossibl.postgres.datetime.ISODateFormat$Parser and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.impossibl.postgres.jdbc.PGArray["resultSet"]->com.impossibl.postgres.jdbc.PGResultSet["statement"]->com.impossibl.postgres.jdbc.PGSimpleStatement["connection"]->com.impossibl.postgres.jdbc.PGConnectionImpl["dateFormatter"]->com.impossibl.postgres.datetime.ISODateFormat["parser"])
```

It seems that logstash jdbc input plugin does not support pgjdbc-ng

**Comment by 1tayH** [comment]
Any way to deal with this (Postgres)? Like @jaykay153 said, the official driver doesn't set `autoCommit` to false when using  `setFetchSize`
I've tried using pgjdbc-ng but since my query is taking too long to complete I'm getting an exception:

```
# my_pipeline.conf
...
jdbc_driver_library => "/usr/share/logstash/drivers/pgjdbc-ng-0.7-complete.jar"
jdbc_driver_class => "com.impossibl.postgres.jdbc.PGDriver"
statement => 'SELECT pg_sleep(600)'
...
```

```
logstash_1  | [2018-11-21T11:06:45,205][ERROR][logstash.inputs.jdbc     ] Java::JavaSql::SQLException: java.nio.channels.ClosedChannelException: SELECT pg_sleep(600)
logstash_1  | [2018-11-21T11:06:45,216][WARN ][logstash.inputs.jdbc     ] Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLException: java.nio.channels.ClosedChannelException>}
logstash_1  | Nov 21, 2018 11:06:48 AM com.impossibl.postgres.jdbc.ThreadedHousekeeper$HousekeeperReference cleanup
logstash_1  | WARNING: Cleaning up leaked connection ( jdbc:pgsql://sndbox-postgres-staging-large.c8zqbprwuvhi.us-east-2.rds.amazonaws.com/ebdb )
logstash_1  | Allocation occurred @
logstash_1  |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
logstash_1  |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
logstash_1  |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
logstash_1  |   at java.lang.reflect.Method.invoke(Method.java:498)
logstash_1  |   at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:423)
```
That being said a simple `select * FROM x` works fine.

**Comment by zalseryani** [comment]
What about oracle , how to change fetch size from the jdbc connection string. 

Any update on this issue !!?!
