### ISSUE TITLE
[FATAL][logstash.runner] When using logstash output to elasticsearch.

### ISSUE THREAD

**Issue by doandk** [logstash-plugins/logstash-input-jdbc#216]
Hello, I'm Doan
ELK 5.4 on Centos 7.

I have installed elasticsearch and running it on port 9200.
I want to get input from mysql with query statement using jdbc plugin and throw it to elasticsearch and create an index.

ref :
https://www.elastic.co/blog/logstash-jdbc-input-plugin

And I have configured one logstash-db.conf file : 

input {
jdbc {

 jdbc_connection_string => "jdbc:mysql://localhost:3306/testdb"
 jdbc_user => "root"
 jdbc_password  => "Welcome1!"
 jdbc_driver_library => "/home/nostra/jdbc/mysql-connector-java-5.1.42-bin.jar"
 jdbc_driver_class => "com.mysql.jdbc.Driver"
 statement => "SELECT * FROM testtable"

      }
}

output {

    elasticsearch {
        index => "test-migrate"
        document_type => "contact"
        document_id => "%{uid}"
        hosts => "http://192.168.100.146:9200"
    }
}

But i faced an error : 

[2017-06-06T17:26:55,795][FATAL][logstash.runner] An unexpected error occurred! {:error=>#<SocketError: initialize: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyTCPServer.java:115:in `initialize'", "org/jruby/RubyIO.java:871:in `new'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/binder.rb:234:in `add_tcp_listener'", "(eval):2:in `add_tcp_listener'", "/usr/share/logstash/logstash-core/lib/logstash/webserver.rb:88:in `start_webserver'", "/usr/share/logstash/logstash-core/lib/logstash/webserver.rb:44:in `run'", "org/jruby/RubyRange.java:479:in `each'", "org/jruby/RubyEnumerable.java:974:in `each_with_index'", "/usr/share/logstash/logstash-core/lib/logstash/webserver.rb:39:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:222:in `start_webserver'"]}

Did i missed something? Can you guys give me a references or guide? 

Thank you.

Doan

**Comment by guyboertje** [comment]
@doandk The error you are getting seems to be coming from in the `runner` of Logstash and not this plugin. Please start a discussion at https://discuss.elastic.co/c/logstash

**Comment by doandk** [comment]
Okay, Thank you @guyboertje
