### ISSUE TITLE
An error occurs when the SQL contains Chinese：【invalid byte sequence in UTF-8】

### ISSUE THREAD

**Issue by limmzsn** [logstash-plugins/logstash-input-jdbc#248]
my sql[ select "中文" as column1,"english" as column2 ]
error trace:
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
{ 2008 rufus-scheduler intercepted an error:
  2008   job:
  2008     Rufus::Scheduler::CronJob "* * * * *" {}
  2008   error:
  2008     2008
  2008     ArgumentError
  2008     invalid byte sequence in UTF-8
  2008       org/jruby/RubyString.java:4152:in `partition'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/sql.rb:578:in `block in placeholder_literal_string_sql_append'
  2008       org/jruby/RubyKernel.java:1292:in `loop'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/sql.rb:577:in `placeholder_literal_string_sql_append'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/sql.rb:96:in `to_s_append'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/sql.rb:1158:in `literal_expression_append'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/sql.rb:86:in `literal_append'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/sql.rb:260:in `literal'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/sql.rb:1483:in `static_sql'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/sql.rb:233:in `select_sql'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/sequel-5.2.0/lib/sequel/dataset/actions.rb:151:in `each'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.0/lib/logstash/plugin_mixins/jdbc.rb:237:in `execute_statement'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.0/lib/logstash/inputs/jdbc.rb:272:in `execute_query'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.0/lib/logstash/inputs/jdbc.rb:250:in `block in run'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block in start_work_thread'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:299:in `block in start_work_thread'
  2008       org/jruby/RubyKernel.java:1292:in `loop'
  2008       /usr/local/limm/logstash/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
  2008   tz:
  2008     ENV['TZ']: 
  2008     Time.now: 2017-11-17 17:08:01 +0800
  2008   scheduler:
  2008     object_id: 2006
  2008     opts:
  2008       {:max_work_threads=>1}
  2008       frequency: 0.3
  2008       scheduler_lock: #<Rufus::Scheduler::NullLock:0x37ec3759>
  2008       trigger_lock: #<Rufus::Scheduler::NullLock:0x57c53a51>
  2008     uptime: 8.559553999999999 (8s559)
  2008     down?: false
  2008     threads: 2
  2008       thread: #<Thread:0x1afbd124>
  2008       thread_key: rufus_scheduler_2006
  2008       work_threads: 1
  2008         active: 1
  2008         vacant: 0
  2008         max_work_threads: 1
  2008       mutexes: {}
  2008     jobs: 1
  2008       at_jobs: 0
  2008       in_jobs: 0
  2008       every_jobs: 0
  2008       interval_jobs: 0
  2008       cron_jobs: 1
  2008     running_jobs: 1
  2008     work_queue: 0
} 2008 .

**Comment by limmzsn** [comment]
我知道怎么解决了：
把sql文件的格式改成utf-8就可以了。（我原来的文件是gb2312格式的）
