### ISSUE TITLE
Double quotes problem in Oracle query

### ISSUE THREAD

**Issue by diegopereiraeng** [logstash-plugins/logstash-input-jdbc#258]
Hi,

I'm using Logstash 6.1 installed using RPM.

I'm using the jdbc-input-plugin native.

I'm doing this query:

Select TO_CHAR(TO_TIMESTAMP(SUBSTR("WRITETIME",2,12),'YYMMDDHH24MISS'), 'DD/MM/YY HH24:MI:SS') as Data, TO_CHAR("System_Name") ,'Busy_CPU' from KLZ_CPU;

But this other query is not working too.

Select "System_Name" from KLZ_CPU;

This is my configuration:

input{
 jdbc{
  jdbc_driver_library => "/tmp/ojdbc6.jar"
  jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
  jdbc_connection_string => "jdbc:oracle:thin:@XXXX:XXXX:XXXXX"
  jdbc_user => "****"
  jdbc_password => "*****"
  schedule => "*/1 * * * *"
  statement => "Select "System_Name" from KLZ_CPU"
  type => "Database"
  tags => ["DW"]
 }
}
output {
         elasticsearch {
                hosts => ["xxxxxx:9200","xxxxxxx:9200"]
                index => "ITM-jdbc-%{+YYYY.MM.dd}"
        }
}

I tried \"System_Name\" , ""System_Name"", without quotes, I don't know what to do!

I get this error:

For ""System_Name"":

[2018-01-04T10:09:33,893][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:MetricasITM, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, {, } at line 9, column 25 (byte 304) after input{\n jdbc{\n  jdbc_driver_library => \"/tmp/ojdbc6.jar\"\n  jdbc_driver_class => \"Java::oracle.jdbc.driver.OracleDriver\"\n  jdbc_connection_string => \"jdbc:oracle:thin:@10.238.116.76:1533:olprg188m1\"\n  jdbc_user => \"\"\n  jdbc_password => \"\"\n  schedule => \"*/1 * * * *\"\n  statement => \"Select \"", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:42:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:50:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:51:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:171:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}

For \"System_Name\":

[2018-01-03T18:20:00,736][ERROR][logstash.inputs.jdbc     ] Java::JavaSql::SQLSyntaxErrorException: ORA-00911: invalid character: SELECT TO_CHAR(TO_TIMESTAMP(SUBSTR(WRITETIME,2,12),'YYMMDDHH24MISS'), 'DD/MM/YY HH24:MI:SS') as Data,\"System_Name\",\"Busy_CPU\" from KLZ_CPU
[2018-01-03T18:20:00,742][WARN ][logstash.inputs.jdbc     ] Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLSyntaxErrorException: ORA-00911: invalid character

For Without double quotes:

[2018-01-04T00:20:00,134][ERROR][logstash.inputs.jdbc     ] Java::JavaSql::SQLSyntaxErrorException: ORA-00904: "BUSY_CPU": invalid identifier: SELECT TO_CHAR(TO_TIMESTAMP(SUBSTR(WRITETIME,2,12),'YYMMDDHH24MISS'), 'DD/MM/YY HH24:MI:SS') as Data, System_Name , Busy_CPU from KLZ_CPU
[2018-01-04T00:20:00,135][WARN ][logstash.inputs.jdbc     ] Exception when executing JDBC query {:exception=>#<Sequel::DatabaseError: Java::JavaSql::SQLSyntaxErrorException: ORA-00904: "BUSY_CPU": invalid identifier

**Comment by diegopereiraeng** [comment]
Solved using statement_filepath => "/etc/logstash/conf.d/query.sql"

I used this query:

Select TO_TIMESTAMP(SUBSTR("WRITETIME",2,12),'YYMMDDHH24MISS') as Data, "System_Name" ,"Busy_CPU"/100 from KLZ_CPU
