### ISSUE TITLE
LogStash::ConfigurationError   2016  org.postgresql.Driver not loaded.

### ISSUE THREAD

**Issue by kop7** [logstash-plugins/logstash-input-jdbc#314]
Hello,

ELK_VERSION = 6.4.2

And I use Docker for elk.
```
root@xxxxxx:/# java -version
openjdk version "1.8.0_181"
------------------------------
bin/logstash-plugin list --verbose
logstash-input-jdbc (4.3.13)

root@xxxxxx:/etc/logstash/conectors# ls
postgresql-9.4-1203.jdbc42.jar
```

postgresql.conf :

```
input {
   jdbc {
     type => 'test'
     jdbc_driver_library => '/etc/logstash/conectors/postgresql-9.4-1203.jdbc42.jar'
     jdbc_driver_class => 'org.postgresql.Driver'
     jdbc_connection_string => 'jdbc:postgresql://host/irongate'
     jdbc_validate_connection => true
     jdbc_user => 'test'
     jdbc_password => 'test'
     jdbc_page_size => '50000'
     schedule => "*/10 * * * *"
     statement_filepath => '/etc/logstash/sql/test.sql'
     use_column_value => true
     tracking_column => 'ad_id'
     tracking_column_type => 'numeric'
     clean_run => true
   }
 }
```

When i run logstash, I get error:

```
2014 rufus-scheduler intercepted an error:
  2014   job:
  2014     Rufus::Scheduler::CronJob "*/10 * * * *" {}
  2014   error:
  2014     2014
  2014     LogStash::ConfigurationError
  2014     org.postgresql.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:163:in `open_jdbc_connection'
{ 2016 rufus-scheduler intercepted an error:
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:221:in `execute_statement'
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:277:in `execute_query'
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:258:in `block in run'
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block in start_work_thread'
  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:299:in `block in start_work_thread'
  2014       org/jruby/RubyKernel.java:1292:in `loop'  2016   job:

  2014       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
  2014   tz:
  2014     ENV['TZ']: 
  2014     Time.now: 2018-11-27 07:50:01 +0000
  2014   scheduler:
  2014     object_id: 2012
  2014     opts:
  2014       {:max_work_threads=>1}
  2014       frequency: 0.3
  2014       scheduler_lock: #<Rufus::Scheduler::NullLock:0x1551fa71>
  2014       trigger_lock: #<Rufus::Scheduler::NullLock:0x29e33dee>
  2016     Rufus::Scheduler::CronJob "*/10 * * * *" {}
  2016   error:
  2016     2016
  2016     LogStash::ConfigurationError
  2016     org.postgresql.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:163:in `open_jdbc_connection'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:221:in `execute_statement'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:277:in `execute_query'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:258:in `block in run'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block in start_work_thread'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:299:in `block in start_work_thread'
  2016       org/jruby/RubyKernel.java:1292:in `loop'
  2016       /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
  2016   tz:
  2016     ENV['TZ']: 
  2016     Time.now: 2018-11-27 07:50:01 +0000
  2016   scheduler:
  2016     object_id: 2010
  2016     opts:
  2016       {:max_work_threads=>1}
  2014     uptime: 385.57016799999997 (6m25s575)
  2016       frequency: 0.3
  2014     down?: false
  2014     threads: 2
  2014       thread: #<Thread:0x311ee0b7>
  2014       thread_key: rufus_scheduler_2012
  2014       work_threads: 1
  2014         active: 1
  2016       scheduler_lock: #<Rufus::Scheduler::NullLock:0x10bc294c>
  2014         vacant: 0
  2014         max_work_threads: 1
  2014       mutexes: {}
  2016       trigger_lock: #<Rufus::Scheduler::NullLock:0x218a0f7d>
  2016     uptime: 385.647306 (6m25s647)
  2016     down?: false
  2016     threads: 2
  2014     jobs: 1
  2016       thread: #<Thread:0x3c225f68>
  2016       thread_key: rufus_scheduler_2010
  2016       work_threads: 1
  2014       at_jobs: 0
  2016         active: 1
  2016         vacant: 0
  2014       in_jobs: 0
  2016         max_work_threads: 1
  2014       every_jobs: 0
  2016       mutexes: {}
  2016     jobs: 1
  2014       interval_jobs: 0
  2016       at_jobs: 0
  2016       in_jobs: 0
  2014       cron_jobs: 1
  2016       every_jobs: 0
  2016       interval_jobs: 0
  2016       cron_jobs: 1
  2014     running_jobs: 1
  2014     work_queue: 0
} 2014 .
  2016     running_jobs: 1
  2016     work_queue: 0
} 2016 .

```

**Comment by kop7** [comment]
Problem solved:

`postgresql-9.4-1203.jdbc42.jar`

rename:

`postgresql-9.4-1203-jdbc42.jar`
