### ISSUE TITLE
[Java::oracle.jdbc.driver.OracleDriver not loaded] Logstash start with error

### ISSUE THREAD

**Issue by aitlp** [logstash-plugins/logstash-input-jdbc#337]
## version
Using logstash 7.1.1 on centos.

## config file

My config file as following:

```
input {
  jdbc {
    jdbc_driver_library => "/home/inspur/elasticsearch/lib/ojdbc6-11.2.0.3.jar"
    jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
    jdbc_connection_string => "jdbc:oracle:thin:@10.47.0.238:1521:orcl"
    jdbc_user => "lgzr"
    jdbc_password => "lgzr"
    statement => "select * from SR_INFOR t"
    clean_run => true
  }
}

output {
   elasticsearch {
      hosts => ["10.47.0.96:9200"]
      index => "data_archives_jdbc"
   }
}
```

## error

```
[2019-06-11T14:37:05,992][ERROR][logstash.javapipeline    ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Jdbc jdbc_user=>"lgzr", jdbc_password=><password>, statement=>"select * from SR_INFOR t", clean_run=>true, jdbc_driver_library=>"/home/inspur/elasticsearch/lib/ojdbc6-11.2.0.3.jar", jdbc_connection_string=>"jdbc:oracle:thin:@10.47.0.238:1521:orcl", id=>"e84563671cbeb6ec2faf944a51248c6c761b91ac3f243d37ac977a095c0f412e", jdbc_driver_class=>"Java::oracle.jdbc.driver.OracleDriver", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_9b659747-af82-47ae-8371-50ee864ddd1a", enable_metric=>true, charset=>"UTF-8">, jdbc_paging_enabled=>false, jdbc_page_size=>100000, jdbc_validate_connection=>false, jdbc_validation_timeout=>3600, jdbc_pool_timeout=>5, sql_log_level=>"info", connection_retry_attempts=>1, connection_retry_attempts_wait_time=>0.5, parameters=>{"sql_last_value"=>1970-01-01 00:00:00 UTC}, last_run_metadata_path=>"/usr/share/logstash/.logstash_jdbc_last_run", use_column_value=>false, tracking_column_type=>"numeric", record_last_run=>true, lowercase_column_names=>true>
  Error: Java::oracle.jdbc.driver.OracleDriver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
  Exception: LogStash::ConfigurationError
  Stack: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:163:in `open_jdbc_connection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/plugin_mixins/jdbc/jdbc.rb:221:in `execute_statement'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:277:in `execute_query'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.13/lib/logstash/inputs/jdbc.rb:263:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:297:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:290:in `block in start_input'
```

Who can tell me what'a the problem? Many thanks.

**Comment by pastatopf** [comment]
For me it worked to put an empty string into the jdbc_driver_library value and to put the ojdbc*jar file into the folder <logstash-home>/logstash-core/lib/jars
