### ISSUE TITLE
logstash6.4 with logstash-input-jdbc start error

### ISSUE THREAD

**Issue by berace** [logstash-plugins/logstash-input-jdbc#375]
## JDBC Input Plugin's Issue Tracker Has Moved

I use logstash-input-jdbc，collect data form mysql to es. An error occurred during startup.
1. logstash6.4
2. mysql driver is mysql-connector-java-5.1.39.jar.

the config is like:

`input {
    jdbc {
	jdbc_connection_string => "jdbc:mysql://***:33063/ec_log"
	jdbc_user => "***"
	jdbc_password => "***"
	jdbc_driver_library => "/data/logstash/config/mysql-connector-java-5.1.39.jar"
	jdbc_driver_class => "com.mysql.jdbc.Driver"
	jdbc_paging_enabled => "true"
	jdbc_default_timezone => "Asia/Shanghai"
	codec => plain { charset => "UTF-8"}
	use_column_value => true
	tracking_column => update_time
	tracking_column_type => timestamp
	record_last_run => true
	last_run_metadata_path => "/data/logstash/config/ec_order_syncpoint"
	statement_filepath => "/data/logstash/config/ec-order.sql"
	clean_run => false
	schedule => "* * * * *"
	type => "ec_order"
    }
} 
output {
	elasticsearch {
		action => "update"
		doc_as_upsert => true
		hosts => ["***:9200","***:9200"]
		index => "***"
		document_id => "%{order_id}"
	}
	stdout { 
		codec => rubydebug
	}
}`

the error logs:

[2020-02-25T14:21:41,421][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>LogStash::ConfigLoadingError, :message=>"The following config files contains non-ascii characters but are not UTF-8 encoded [\"/data/logstash/config/mysql-connector-java-5.1.39.jar\"]", :backtrace=>["/usr/local/logstash-6.4.0/logstash-core/lib/logstash/config/source/local.rb:83:in `read'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/config/source/local.rb:94:in `read'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/config/source/local.rb:190:in `local_pipeline_configs'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/config/source/local.rb:161:in `pipeline_configs'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/config/source_loader.rb:61:in `block in fetch'", "org/jruby/RubyArray.java:2481:in `collect'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/config/source_loader.rb:60:in `fetch'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/agent.rb:142:in `converge_state_and_update'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/agent.rb:110:in `block in execute'", "/usr/local/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:18:in `interval'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/agent.rb:99:in `execute'", "/usr/local/logstash-6.4.0/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/local/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
[2020-02-25T14:21:41,422][DEBUG][logstash.agent           ] Could not fetch the configuration to converge, will retry {:message=>"The following config files contains non-ascii characters but are not UTF-8 encoded [\"/data/logstash/config/mysql-connector-java-5.1.39.jar\"]", :retrying_in=>3.0}

It took me a long time to find no reason.
Can anyone help me out. a lot tks.

[integration-source]: https://github.com/logstash-plugins/logstash-integration-jdbc
[integration-issues]: https://github.com/logstash-plugins/logstash-integration-jdbc/issues/
[logstash-forum]: https://discuss.elastic.co/c/logstash

**Comment by berace** [comment]
The cause of the problem was found.
the jar contained in the conf directory.
